apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xkr6iyhii-python
  janus-idp.io/tekton: xkr6iyhii-python
  backstage.io/kubernetes-id: xkr6iyhii-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xkr6iyhii-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
