apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xkr6iyhii-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:9f59f3664b7d8278c53c7b17676d07a03beea642@sha256:08b97dd1ebcec7ca27fadc30dd6f3c308d28f8802319cd204f143aad682ede1f
          name: container-image
